/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author ROMI
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xMouse, yMouse;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackground = new javax.swing.JPanel();
        jPCuerpo = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jLCargo = new javax.swing.JLabel();
        jCBCargo = new javax.swing.JComboBox<>();
        jTFUsuario = new javax.swing.JTextField();
        jTContraseña = new javax.swing.JTextField();
        jLBtnIniciarSesion = new javax.swing.JLabel();
        jLIconoLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLMinimiza = new javax.swing.JLabel();
        jLCierra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPBackground.setPreferredSize(new java.awt.Dimension(570, 400));
        jPBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        jPCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLUsuario.setText("Usuario:");
        jPCuerpo.add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLContraseña.setText("Contraseña:");
        jPCuerpo.add(jLContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCargo.setForeground(new java.awt.Color(0, 0, 0));
        jLCargo.setText("Cargo:");
        jPCuerpo.add(jLCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jPCuerpo.add(jCBCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, -1));

        jTFUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFUsuarioMouseClicked(evt);
            }
        });
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });
        jPCuerpo.add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 170, -1));

        jTContraseña.setForeground(new java.awt.Color(51, 51, 76));
        jPCuerpo.add(jTContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, -1));

        jLBtnIniciarSesion.setBackground(new java.awt.Color(0, 150, 136));
        jLBtnIniciarSesion.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLBtnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLBtnIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBtnIniciarSesion.setText("Iniciar sesión");
        jLBtnIniciarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLBtnIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jLBtnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBtnIniciarSesion.setOpaque(true);
        jPCuerpo.add(jLBtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 117, 26));

        jLIconoLogin.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLIconoLogin.setForeground(new java.awt.Color(0, 150, 136));
        jLIconoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIconoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios-alt.png"))); // NOI18N
        jLIconoLogin.setText("Login");
        jLIconoLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLIconoLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPCuerpo.add(jLIconoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 120));

        jPanel1.setBackground(new java.awt.Color(0, 150, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMinimiza.setBackground(new java.awt.Color(0, 150, 136));
        jLMinimiza.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLMinimiza.setForeground(new java.awt.Color(255, 255, 255));
        jLMinimiza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMinimiza.setText("_");
        jLMinimiza.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLMinimiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLMinimiza.setOpaque(true);
        jLMinimiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMinimizaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMinimizaMouseExited(evt);
            }
        });
        jPanel1.add(jLMinimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 29, 30));

        jLCierra.setBackground(new java.awt.Color(0, 150, 136));
        jLCierra.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLCierra.setForeground(new java.awt.Color(255, 255, 255));
        jLCierra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCierra.setText("X");
        jLCierra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCierra.setOpaque(true);
        jLCierra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCierraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCierraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCierraMouseExited(evt);
            }
        });
        jPanel1.add(jLCierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 30, 30));

        jPCuerpo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPBackground.add(jPCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 350, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mauri\\Desktop\\Banner FM.png")); // NOI18N
        jPBackground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jTFUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFUsuarioMouseClicked
        if(jTFUsuario.getText().equals("Ingrese su usuario")){
            jTFUsuario.setText("");
            jTFUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTFUsuarioMouseClicked

    private void jLCierraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCierraMouseExited
        jLCierra.setOpaque(false);
        jLCierra.setBackground(new Color(0,150,136));
    }//GEN-LAST:event_jLCierraMouseExited

    private void jLCierraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCierraMouseEntered
        jLCierra.setOpaque(true);
        jLCierra.setBackground(Color.red);
    }//GEN-LAST:event_jLCierraMouseEntered

    private void jLCierraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCierraMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLCierraMouseClicked

    private void jLMinimizaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizaMouseExited
        jLMinimiza.setOpaque(false);
        jLMinimiza.setBackground(new Color(0,150,136));
    }//GEN-LAST:event_jLMinimizaMouseExited

    private void jLMinimizaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizaMouseEntered
        jLMinimiza.setOpaque(true);
        jLMinimiza.setBackground(new Color(10,160,140));
    }//GEN-LAST:event_jLMinimizaMouseEntered

    private void jLMinimizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizaMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jLMinimizaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBCargo;
    private javax.swing.JLabel jLBtnIniciarSesion;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLCierra;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLIconoLogin;
    private javax.swing.JLabel jLMinimiza;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPCuerpo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTContraseña;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
