/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.ProductoData;
import Entidades.Producto;
import Utilidades.TablaFraveMax;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROMI
 */
public class Menu extends javax.swing.JFrame {

    private ProductoData pd = new ProductoData();
    private Producto p = null;
    private int xMouse, yMouse;
    Color verdeBase = new Color(0,150,136);
    Color verdeClaro = new Color(10, 170, 140);
    Color grisBase = new Color(51, 51, 76);
    Color grisClaro = new Color(66, 66, 76);

    public DefaultTableModel Modelo = new DefaultTableModel(
            null,
            new String[]{
                "ID", "Nombre", "Descripcion", "Precio Actual", "Stock"
            }
    ) {
        public boolean isCellEditable(int fila, int column) {
            return false;
        }

        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
        };

        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }
    };

    private void llenarTabla() {
        for (Producto pro : pd.listarProducto()) {
            Modelo.addRow(new Object[]{pro.getIdProducto(), pro.getNombreProducto(),
                pro.getDescripcion(), pro.getPrecioActual(), pro.getStock()});
            jtListaPro.setModel(Modelo);
        }
    }

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtListaPro.setModel(Modelo);
        llenarText();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jPanelFravemax = new javax.swing.JPanel();
        jlSalir = new javax.swing.JLabel();
        jlMinimizar = new javax.swing.JLabel();
        fravemaxLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jlProductos = new javax.swing.JLabel();
        jlClientes = new javax.swing.JLabel();
        jlVentas = new javax.swing.JLabel();
        jlCerrarSesion = new javax.swing.JLabel();
        jlInicio = new javax.swing.JLabel();
        jtpEscritorio = new javax.swing.JTabbedPane();
        jtpInicio = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verMasC = new javax.swing.JLabel();
        verMasV = new javax.swing.JLabel();
        verMasP = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtpVentas = new javax.swing.JPanel();
        jlGestionV = new javax.swing.JLabel();
        jlVentaIcon1 = new javax.swing.JLabel();
        jlRegistrar = new javax.swing.JLabel();
        textVentaA = new javax.swing.JLabel();
        textVentaD = new javax.swing.JLabel();
        textVentaE = new javax.swing.JLabel();
        RegistrarVenta = new javax.swing.JLabel();
        DetVenta = new javax.swing.JLabel();
        EliminarVenta = new javax.swing.JLabel();
        jlEliminarVenta = new javax.swing.JLabel();
        jlVentaIcon3 = new javax.swing.JLabel();
        rectanguloV1 = new javax.swing.JLabel();
        jlVentaIcon2 = new javax.swing.JLabel();
        jlDetalles = new javax.swing.JLabel();
        rectanguloV2 = new javax.swing.JLabel();
        rectanguloV3 = new javax.swing.JLabel();
        jlListarVenta = new javax.swing.JLabel();
        jtpClientes = new javax.swing.JPanel();
        jlListarCliente = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jlAgregarCliente = new javax.swing.JLabel();
        jlModificarCliente = new javax.swing.JLabel();
        jlEliminarCliente = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        textClienteE = new javax.swing.JLabel();
        textClienteM = new javax.swing.JLabel();
        textClienteA = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jtpProductos = new javax.swing.JPanel();
        jlListar = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlAgregar = new javax.swing.JLabel();
        jlModificar = new javax.swing.JLabel();
        jlEliminar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textE = new javax.swing.JLabel();
        textM = new javax.swing.JLabel();
        textA = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtpListaP = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        jtListaPro = new TablaFraveMax();
        jtfBuscador = new javax.swing.JTextField();
        jlBusqueda = new javax.swing.JLabel();
        jtpAgregarPro = new javax.swing.JPanel();
        jLAgregarProducto = new javax.swing.JLabel();
        jLNombreProductoAP = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLDescripcionAP = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLPrecioActualAP = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLStockAP = new javax.swing.JLabel();
        jLBtnAgregarProd = new javax.swing.JLabel();
        jTFNombreProductoAgrProd = new javax.swing.JTextField();
        jTFDescripcionAgrProd = new javax.swing.JTextField();
        jTFPrecioActualAgrProd = new javax.swing.JTextField();
        jTFStockAgrProd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtpModPro = new javax.swing.JPanel();
        jLModificarProd = new javax.swing.JLabel();
        jLBuscarProdModProd = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jTFNombreProdModProd = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTFDescripcionModProd = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTFPrecioActualModProd = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTFStockModProd = new javax.swing.JTextField();
        jLNombreProdModProd = new javax.swing.JLabel();
        jLDescripcionModProd = new javax.swing.JLabel();
        jLPrecioActualModProd = new javax.swing.JLabel();
        jLStockModProd = new javax.swing.JLabel();
        jLBtnModificarModProd = new javax.swing.JLabel();
        jcbProductos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFravemax.setBackground(new java.awt.Color(0, 150, 136));
        jPanelFravemax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFravemax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelFravemaxMouseDragged(evt);
            }
        });
        jPanelFravemax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFravemaxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelFravemaxMouseReleased(evt);
            }
        });
        jPanelFravemax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlSalir.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("X");
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
        });
        jPanelFravemax.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 30));

        jlMinimizar.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jlMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setText("_");
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseExited(evt);
            }
        });
        jPanelFravemax.add(jlMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 30));

        fravemaxLogo.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        fravemaxLogo.setForeground(new java.awt.Color(255, 255, 255));
        fravemaxLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fravemaxLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fravemax.png"))); // NOI18N
        fravemaxLogo.setText("BIENVENIDO A FRAVEMAX");
        fravemaxLogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fravemaxLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fravemaxLogo.setIconTextGap(0);
        fravemaxLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelFravemax.add(fravemaxLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -3, 170, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanelFravemax.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanelFravemax.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 100));

        jPanelUsuario.setBackground(new java.awt.Color(0, 150, 136));
        jPanelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/circulo-de-usuario.png"))); // NOI18N
        jLabel5.setText("Nombre de Usuario");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setIconTextGap(6);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jPanelFravemax.add(jPanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        BackGround.add(jPanelFravemax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jPanelOpciones.setBackground(new java.awt.Color(51, 51, 76));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlProductos.setBackground(new java.awt.Color(51, 51, 76));
        jlProductos.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlProductos.setForeground(new java.awt.Color(255, 255, 255));
        jlProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Productos.png"))); // NOI18N
        jlProductos.setText("Productos");
        jlProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlProductos.setIconTextGap(15);
        jlProductos.setOpaque(true);
        jlProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlProductosMouseExited(evt);
            }
        });
        jPanelOpciones.add(jlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 40));

        jlClientes.setBackground(new java.awt.Color(51, 51, 76));
        jlClientes.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlClientes.setForeground(new java.awt.Color(255, 255, 255));
        jlClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios.png"))); // NOI18N
        jlClientes.setText("Clientes");
        jlClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlClientes.setIconTextGap(15);
        jlClientes.setOpaque(true);
        jlClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlClientesMouseExited(evt);
            }
        });
        jPanelOpciones.add(jlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 40));

        jlVentas.setBackground(new java.awt.Color(51, 51, 76));
        jlVentas.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlVentas.setForeground(new java.awt.Color(255, 255, 255));
        jlVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/carrito-de-compras.png"))); // NOI18N
        jlVentas.setText("Ventas");
        jlVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlVentas.setIconTextGap(15);
        jlVentas.setOpaque(true);
        jlVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasMouseExited(evt);
            }
        });
        jPanelOpciones.add(jlVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 40));

        jlCerrarSesion.setBackground(new java.awt.Color(51, 51, 76));
        jlCerrarSesion.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jlCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/salir-alt.png"))); // NOI18N
        jlCerrarSesion.setText("Cerrar Sesion");
        jlCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlCerrarSesion.setIconTextGap(15);
        jlCerrarSesion.setOpaque(true);
        jlCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCerrarSesionMouseExited(evt);
            }
        });
        jPanelOpciones.add(jlCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 40));

        jlInicio.setBackground(new java.awt.Color(51, 51, 76));
        jlInicio.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlInicio.setForeground(new java.awt.Color(255, 255, 255));
        jlInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Inicio.png"))); // NOI18N
        jlInicio.setText("Inicio");
        jlInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlInicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlInicio.setIconTextGap(15);
        jlInicio.setOpaque(true);
        jlInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlInicioMouseExited(evt);
            }
        });
        jPanelOpciones.add(jlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 40));

        BackGround.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 200, 420));

        jtpInicio.setBackground(new java.awt.Color(255, 255, 255));
        jtpInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plataforma-rodante-alternativa.png"))); // NOI18N
        jtpInicio.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 150));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flecha-del-carrito-hacia-abajo.png"))); // NOI18N
        jtpInicio.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 150));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios-alt.png"))); // NOI18N
        jtpInicio.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 180, 150));

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Clientes");
        jtpInicio.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Ventas");
        jtpInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Productos");
        jtpInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        verMasC.setBackground(new java.awt.Color(0, 150, 136));
        verMasC.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        verMasC.setForeground(new java.awt.Color(255, 255, 255));
        verMasC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verMasC.setText("Ver mas");
        verMasC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        verMasC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        verMasC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verMasC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verMasC.setOpaque(true);
        verMasC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verMasC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMasCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMasCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verMasCMouseExited(evt);
            }
        });
        jtpInicio.add(verMasC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, 30));

        verMasV.setBackground(new java.awt.Color(0, 150, 136));
        verMasV.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        verMasV.setForeground(new java.awt.Color(255, 255, 255));
        verMasV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verMasV.setText("Ver mas");
        verMasV.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        verMasV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        verMasV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verMasV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verMasV.setOpaque(true);
        verMasV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verMasV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMasVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMasVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verMasVMouseExited(evt);
            }
        });
        jtpInicio.add(verMasV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, 30));

        verMasP.setBackground(new java.awt.Color(0, 150, 136));
        verMasP.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        verMasP.setForeground(new java.awt.Color(255, 255, 255));
        verMasP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verMasP.setText("Ver mas");
        verMasP.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        verMasP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        verMasP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verMasP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verMasP.setOpaque(true);
        verMasP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verMasP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMasPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMasPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verMasPMouseExited(evt);
            }
        });
        jtpInicio.add(verMasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 30));

        text3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        text3.setForeground(new java.awt.Color(153, 153, 153));
        text3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpInicio.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 90));

        text2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        text2.setForeground(new java.awt.Color(153, 153, 153));
        text2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpInicio.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 150, 90));

        text1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        text1.setForeground(new java.awt.Color(153, 153, 153));
        text1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtpInicio.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 90));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Gestion de ...");
        jtpInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jtpEscritorio.addTab("tab1", jtpInicio);

        jtpVentas.setBackground(new java.awt.Color(255, 255, 255));
        jtpVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlGestionV.setBackground(new java.awt.Color(102, 102, 102));
        jlGestionV.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jlGestionV.setForeground(new java.awt.Color(153, 153, 153));
        jlGestionV.setText("Gestion de Ventas");
        jtpVentas.add(jlGestionV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 30));

        jlVentaIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlVentaIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lista-del-portapapeles.png"))); // NOI18N
        jtpVentas.add(jlVentaIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 150));

        jlRegistrar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jlRegistrar.setForeground(new java.awt.Color(102, 102, 102));
        jlRegistrar.setText("Registrar");
        jtpVentas.add(jlRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        textVentaA.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textVentaA.setForeground(new java.awt.Color(153, 153, 153));
        textVentaA.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textVentaA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtpVentas.add(textVentaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 90));

        textVentaD.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textVentaD.setForeground(new java.awt.Color(153, 153, 153));
        textVentaD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpVentas.add(textVentaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 150, 90));

        textVentaE.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textVentaE.setForeground(new java.awt.Color(153, 153, 153));
        textVentaE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpVentas.add(textVentaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 90));

        RegistrarVenta.setBackground(new java.awt.Color(0, 150, 136));
        RegistrarVenta.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        RegistrarVenta.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarVenta.setText("Registrar");
        RegistrarVenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegistrarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        RegistrarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegistrarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarVenta.setOpaque(true);
        RegistrarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegistrarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarVentaMouseExited(evt);
            }
        });
        jtpVentas.add(RegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 30));

        DetVenta.setBackground(new java.awt.Color(0, 150, 136));
        DetVenta.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        DetVenta.setForeground(new java.awt.Color(255, 255, 255));
        DetVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetVenta.setText("Detallar");
        DetVenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DetVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        DetVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DetVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DetVenta.setOpaque(true);
        DetVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DetVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DetVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DetVentaMouseExited(evt);
            }
        });
        jtpVentas.add(DetVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, 30));

        EliminarVenta.setBackground(new java.awt.Color(0, 150, 136));
        EliminarVenta.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        EliminarVenta.setForeground(new java.awt.Color(255, 255, 255));
        EliminarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarVenta.setText("Eliminar");
        EliminarVenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EliminarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        EliminarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EliminarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarVenta.setOpaque(true);
        EliminarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarVentaMouseExited(evt);
            }
        });
        jtpVentas.add(EliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, 30));

        jlEliminarVenta.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jlEliminarVenta.setForeground(new java.awt.Color(102, 102, 102));
        jlEliminarVenta.setText("Eliminar");
        jtpVentas.add(jlEliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jlVentaIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlVentaIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/archivo-menos.png"))); // NOI18N
        jtpVentas.add(jlVentaIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 180, 150));

        rectanguloV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpVentas.add(rectanguloV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jlVentaIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlVentaIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/informacion-del-circulo-de-archivos.png"))); // NOI18N
        jtpVentas.add(jlVentaIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 150));

        jlDetalles.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jlDetalles.setForeground(new java.awt.Color(102, 102, 102));
        jlDetalles.setText("Detalles");
        jtpVentas.add(jlDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        rectanguloV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpVentas.add(rectanguloV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        rectanguloV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpVentas.add(rectanguloV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jlListarVenta.setBackground(new java.awt.Color(0, 150, 136));
        jlListarVenta.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlListarVenta.setForeground(new java.awt.Color(255, 255, 255));
        jlListarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListarVenta.setText("Listar Ventas");
        jlListarVenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlListarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlListarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlListarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlListarVenta.setOpaque(true);
        jlListarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlListarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlListarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlListarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlListarVentaMouseExited(evt);
            }
        });
        jtpVentas.add(jlListarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 120, 30));

        jtpEscritorio.addTab("tab2", jtpVentas);

        jtpClientes.setBackground(new java.awt.Color(255, 255, 255));
        jtpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlListarCliente.setBackground(new java.awt.Color(0, 150, 136));
        jlListarCliente.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlListarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlListarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListarCliente.setText("Listar Clientes");
        jlListarCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlListarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlListarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlListarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlListarCliente.setOpaque(true);
        jlListarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlListarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlListarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlListarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlListarClienteMouseExited(evt);
            }
        });
        jtpClientes.add(jlListarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 120, 30));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/borrar-usuario.png"))); // NOI18N
        jtpClientes.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 180, 150));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/agregar-usuario.png"))); // NOI18N
        jtpClientes.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 150));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editar-usuario.png"))); // NOI18N
        jtpClientes.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 150));

        jlAgregarCliente.setBackground(new java.awt.Color(0, 150, 136));
        jlAgregarCliente.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlAgregarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAgregarCliente.setText("Agregar");
        jlAgregarCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlAgregarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlAgregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlAgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlAgregarCliente.setOpaque(true);
        jlAgregarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAgregarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAgregarClienteMouseExited(evt);
            }
        });
        jtpClientes.add(jlAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 30));

        jlModificarCliente.setBackground(new java.awt.Color(0, 150, 136));
        jlModificarCliente.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlModificarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlModificarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlModificarCliente.setText("Modificar");
        jlModificarCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlModificarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlModificarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlModificarCliente.setOpaque(true);
        jlModificarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlModificarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlModificarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlModificarClienteMouseExited(evt);
            }
        });
        jtpClientes.add(jlModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, 30));

        jlEliminarCliente.setBackground(new java.awt.Color(0, 150, 136));
        jlEliminarCliente.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlEliminarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEliminarCliente.setText("Eliminar");
        jlEliminarCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlEliminarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlEliminarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlEliminarCliente.setOpaque(true);
        jlEliminarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlEliminarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlEliminarClienteMouseExited(evt);
            }
        });
        jtpClientes.add(jlEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, 30));

        jLabel28.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("Gestion de Clientes");
        jtpClientes.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 30));

        textClienteE.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textClienteE.setForeground(new java.awt.Color(153, 153, 153));
        textClienteE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpClientes.add(textClienteE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 90));

        textClienteM.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textClienteM.setForeground(new java.awt.Color(153, 153, 153));
        textClienteM.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpClientes.add(textClienteM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 150, 90));

        textClienteA.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textClienteA.setForeground(new java.awt.Color(153, 153, 153));
        textClienteA.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpClientes.add(textClienteA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 90));

        jLabel29.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Modificar ");
        jtpClientes.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 80, -1));

        jLabel30.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Eliminar ");
        jtpClientes.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel31.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Agregar ");
        jtpClientes.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpClientes.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpClientes.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpClientes.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jtpEscritorio.addTab("tab3", jtpClientes);

        jtpProductos.setBackground(new java.awt.Color(255, 255, 255));
        jtpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlListar.setBackground(new java.awt.Color(0, 150, 136));
        jlListar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlListar.setForeground(new java.awt.Color(255, 255, 255));
        jlListar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListar.setText("Listar Productos");
        jlListar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlListar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlListar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlListar.setOpaque(true);
        jlListar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlListarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlListarMouseExited(evt);
            }
        });
        jtpProductos.add(jlListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 120, 30));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/basura.png"))); // NOI18N
        jtpProductos.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 180, 150));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/agregar-documento.png"))); // NOI18N
        jtpProductos.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 150));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/archivo-de-edicion.png"))); // NOI18N
        jtpProductos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, 150));

        jlAgregar.setBackground(new java.awt.Color(0, 150, 136));
        jlAgregar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jlAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAgregar.setText("Agregar");
        jlAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlAgregar.setOpaque(true);
        jlAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAgregarMouseExited(evt);
            }
        });
        jtpProductos.add(jlAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 30));

        jlModificar.setBackground(new java.awt.Color(0, 150, 136));
        jlModificar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlModificar.setForeground(new java.awt.Color(255, 255, 255));
        jlModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlModificar.setText("Modificar");
        jlModificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlModificar.setOpaque(true);
        jlModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlModificarMouseExited(evt);
            }
        });
        jtpProductos.add(jlModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, 30));

        jlEliminar.setBackground(new java.awt.Color(0, 150, 136));
        jlEliminar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jlEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEliminar.setText("Eliminar");
        jlEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        jlEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlEliminar.setOpaque(true);
        jlEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlEliminarMouseExited(evt);
            }
        });
        jtpProductos.add(jlEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 80, 30));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Gestion de Productos");
        jtpProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, 30));

        textE.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textE.setForeground(new java.awt.Color(153, 153, 153));
        textE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpProductos.add(textE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 90));

        textM.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textM.setForeground(new java.awt.Color(153, 153, 153));
        textM.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpProductos.add(textM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 150, 90));

        textA.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        textA.setForeground(new java.awt.Color(153, 153, 153));
        textA.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpProductos.add(textA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 90));

        jLabel16.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Modificar ");
        jtpProductos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 80, -1));

        jLabel17.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Eliminar ");
        jtpProductos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Agregar ");
        jtpProductos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpProductos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpProductos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpProductos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jtpEscritorio.addTab("tab4", jtpProductos);

        jtpListaP.setBackground(new java.awt.Color(255, 255, 255));
        jtpListaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Lista de Productos activos");
        jtpListaP.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Scroll.setBackground(new java.awt.Color(255, 255, 255));
        Scroll.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        jtListaPro.setBackground(new java.awt.Color(204, 204, 204));
        jtListaPro.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jtListaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListaPro.setGridColor(new java.awt.Color(0, 102, 102));
        jtListaPro.setMinimumSize(new java.awt.Dimension(60, 60));
        Scroll.setViewportView(jtListaPro);

        jtpListaP.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 120, 570, 290));

        jtfBuscador.setBackground(new java.awt.Color(255, 255, 255));
        jtfBuscador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtpListaP.add(jtfBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 160, 30));

        jlBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jlBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/busqueda - gris.png"))); // NOI18N
        jlBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBusqueda.setOpaque(true);
        jlBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBusquedaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBusquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBusquedaMouseExited(evt);
            }
        });
        jtpListaP.add(jlBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 30, 30));

        jtpEscritorio.addTab("tab5", jtpListaP);

        jtpAgregarPro.setBackground(new java.awt.Color(255, 255, 255));
        jtpAgregarPro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAgregarProducto.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLAgregarProducto.setForeground(new java.awt.Color(153, 153, 153));
        jLAgregarProducto.setText("Agregar producto");
        jtpAgregarPro.add(jLAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 38));

        jLNombreProductoAP.setBackground(new java.awt.Color(153, 153, 153));
        jLNombreProductoAP.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLNombreProductoAP.setForeground(new java.awt.Color(153, 153, 153));
        jLNombreProductoAP.setText("Nombre de el producto:");
        jtpAgregarPro.add(jLNombreProductoAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 24));

        jSeparator4.setBackground(new java.awt.Color(0, 150, 136));
        jtpAgregarPro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 210, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 150, 136));
        jtpAgregarPro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, 20));

        jLDescripcionAP.setBackground(new java.awt.Color(153, 153, 153));
        jLDescripcionAP.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLDescripcionAP.setForeground(new java.awt.Color(153, 153, 153));
        jLDescripcionAP.setText("Descripción:");
        jtpAgregarPro.add(jLDescripcionAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 24));

        jSeparator6.setBackground(new java.awt.Color(0, 150, 136));
        jtpAgregarPro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 210, 20));

        jLPrecioActualAP.setBackground(new java.awt.Color(153, 153, 153));
        jLPrecioActualAP.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLPrecioActualAP.setForeground(new java.awt.Color(153, 153, 153));
        jLPrecioActualAP.setText("Precio Actual:");
        jtpAgregarPro.add(jLPrecioActualAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 24));

        jSeparator7.setBackground(new java.awt.Color(0, 150, 136));
        jtpAgregarPro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, 20));

        jLStockAP.setBackground(new java.awt.Color(153, 153, 153));
        jLStockAP.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLStockAP.setForeground(new java.awt.Color(153, 153, 153));
        jLStockAP.setText("Stock:");
        jtpAgregarPro.add(jLStockAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 24));

        jLBtnAgregarProd.setBackground(new java.awt.Color(0, 150, 136));
        jLBtnAgregarProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLBtnAgregarProd.setForeground(new java.awt.Color(255, 255, 255));
        jLBtnAgregarProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBtnAgregarProd.setText("Agregar");
        jLBtnAgregarProd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLBtnAgregarProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBtnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBtnAgregarProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLBtnAgregarProd.setOpaque(true);
        jLBtnAgregarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBtnAgregarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBtnAgregarProdMouseExited(evt);
            }
        });
        jtpAgregarPro.add(jLBtnAgregarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 350, 80, 30));

        jTFNombreProductoAgrProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFNombreProductoAgrProd.setBorder(null);
        jtpAgregarPro.add(jTFNombreProductoAgrProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 210, 20));

        jTFDescripcionAgrProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFDescripcionAgrProd.setBorder(null);
        jtpAgregarPro.add(jTFDescripcionAgrProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, 20));

        jTFPrecioActualAgrProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFPrecioActualAgrProd.setBorder(null);
        jtpAgregarPro.add(jTFPrecioActualAgrProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 20));

        jTFStockAgrProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFStockAgrProd.setBorder(null);
        jtpAgregarPro.add(jTFStockAgrProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 210, 20));

        jtpEscritorio.addTab("tab6", jtpAgregarPro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jtpEscritorio.addTab("tab7", jPanel2);

        jtpModPro.setBackground(new java.awt.Color(255, 255, 255));
        jtpModPro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLModificarProd.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLModificarProd.setForeground(new java.awt.Color(153, 153, 153));
        jLModificarProd.setText("Modificar producto");
        jtpModPro.add(jLModificarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 43));

        jLBuscarProdModProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLBuscarProdModProd.setForeground(new java.awt.Color(153, 153, 153));
        jLBuscarProdModProd.setText("Buscar producto");
        jtpModPro.add(jLBuscarProdModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 150, 136));
        jSeparator8.setOpaque(true);
        jSeparator8.setPreferredSize(new java.awt.Dimension(50, 2));
        jtpModPro.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, -1));

        jTFNombreProdModProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFNombreProdModProd.setBorder(null);
        jtpModPro.add(jTFNombreProdModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 150, 136));
        jSeparator9.setOpaque(true);
        jSeparator9.setPreferredSize(new java.awt.Dimension(50, 2));
        jtpModPro.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 200, -1));

        jTFDescripcionModProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFDescripcionModProd.setBorder(null);
        jtpModPro.add(jTFDescripcionModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 200, 30));

        jSeparator10.setBackground(new java.awt.Color(0, 150, 136));
        jSeparator10.setOpaque(true);
        jSeparator10.setPreferredSize(new java.awt.Dimension(50, 2));
        jtpModPro.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, -1));

        jTFPrecioActualModProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFPrecioActualModProd.setBorder(null);
        jtpModPro.add(jTFPrecioActualModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 150, 136));
        jSeparator11.setOpaque(true);
        jSeparator11.setPreferredSize(new java.awt.Dimension(50, 2));
        jtpModPro.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 200, -1));

        jTFStockModProd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTFStockModProd.setBorder(null);
        jtpModPro.add(jTFStockModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 200, 30));

        jLNombreProdModProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLNombreProdModProd.setForeground(new java.awt.Color(153, 153, 153));
        jLNombreProdModProd.setText("Nombre producto");
        jtpModPro.add(jLNombreProdModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLDescripcionModProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLDescripcionModProd.setForeground(new java.awt.Color(153, 153, 153));
        jLDescripcionModProd.setText("Descripción");
        jtpModPro.add(jLDescripcionModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLPrecioActualModProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLPrecioActualModProd.setForeground(new java.awt.Color(153, 153, 153));
        jLPrecioActualModProd.setText("Precio Actual");
        jtpModPro.add(jLPrecioActualModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLStockModProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLStockModProd.setForeground(new java.awt.Color(153, 153, 153));
        jLStockModProd.setText("Stock");
        jtpModPro.add(jLStockModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLBtnModificarModProd.setBackground(new java.awt.Color(0, 150, 136));
        jLBtnModificarModProd.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLBtnModificarModProd.setForeground(new java.awt.Color(255, 255, 255));
        jLBtnModificarModProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBtnModificarModProd.setText("Modificar");
        jLBtnModificarModProd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLBtnModificarModProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBtnModificarModProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBtnModificarModProd.setOpaque(true);
        jLBtnModificarModProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBtnModificarModProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBtnModificarModProdMouseExited(evt);
            }
        });
        jtpModPro.add(jLBtnModificarModProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 100, 30));

        jcbProductos.setBackground(new java.awt.Color(255, 255, 255));
        jcbProductos.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jcbProductos.setForeground(new java.awt.Color(0, 102, 102));
        jtpModPro.add(jcbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 30));

        jtpEscritorio.addTab("tab8", jtpModPro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jtpEscritorio.addTab("tab9", jPanel1);

        BackGround.add(jtpEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 53, 600, 450));

        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMouseEntered
        jlVentas.setBackground(grisClaro);
    }//GEN-LAST:event_jlVentasMouseEntered

    private void jlVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMouseExited
        jlVentas.setBackground(grisBase);
    }//GEN-LAST:event_jlVentasMouseExited

    private void jlClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseEntered
        jlClientes.setBackground(grisClaro);
    }//GEN-LAST:event_jlClientesMouseEntered

    private void jlClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseExited
        jlClientes.setBackground(grisBase);
    }//GEN-LAST:event_jlClientesMouseExited

    private void jlCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarSesionMouseEntered
        jlCerrarSesion.setBackground(grisClaro);
    }//GEN-LAST:event_jlCerrarSesionMouseEntered

    private void jlCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarSesionMouseExited
        jlCerrarSesion.setBackground(grisBase);
    }//GEN-LAST:event_jlCerrarSesionMouseExited

    private void jlVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMouseClicked
        jtpEscritorio.setSelectedIndex(1);
    }//GEN-LAST:event_jlVentasMouseClicked

    private void jlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseClicked
        jtpEscritorio.setSelectedIndex(2);
    }//GEN-LAST:event_jlClientesMouseClicked

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        jlSalir.setOpaque(true);
        jlSalir.setBackground(Color.red);
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        jlSalir.setOpaque(false);
        jlSalir.setBackground(verdeBase);
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseEntered
        jlMinimizar.setOpaque(true);
        jlMinimizar.setBackground(verdeClaro);
    }//GEN-LAST:event_jlMinimizarMouseEntered

    private void jlMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseExited
        jlMinimizar.setOpaque(false);
        jlMinimizar.setBackground(verdeBase);
    }//GEN-LAST:event_jlMinimizarMouseExited

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseEntered
        jlInicio.setBackground(grisClaro);
    }//GEN-LAST:event_jlInicioMouseEntered

    private void jlInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseExited
        jlInicio.setBackground(grisBase);
    }//GEN-LAST:event_jlInicioMouseExited

    private void jlInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseClicked
        jtpEscritorio.setSelectedIndex(0);
    }//GEN-LAST:event_jlInicioMouseClicked

    private void jPanelFravemaxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFravemaxMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        jPanelFravemax.setCursor(new Cursor(MOVE_CURSOR));
    }//GEN-LAST:event_jPanelFravemaxMousePressed

    private void jPanelFravemaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFravemaxMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelFravemaxMouseDragged

    private void jPanelFravemaxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFravemaxMouseReleased
        jPanelFravemax.setCursor(new Cursor(DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelFravemaxMouseReleased

    private void verMasPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasPMouseEntered
        verMasP.setBackground(verdeClaro);
    }//GEN-LAST:event_verMasPMouseEntered

    private void verMasPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasPMouseExited
        verMasP.setBackground(verdeBase);
    }//GEN-LAST:event_verMasPMouseExited

    private void verMasVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasVMouseEntered
        verMasV.setBackground(verdeClaro);
    }//GEN-LAST:event_verMasVMouseEntered

    private void verMasVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasVMouseExited
        verMasV.setBackground(verdeBase);
    }//GEN-LAST:event_verMasVMouseExited

    private void verMasCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasCMouseEntered
        verMasC.setBackground(verdeClaro);
    }//GEN-LAST:event_verMasCMouseEntered

    private void verMasCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasCMouseExited
        verMasC.setBackground(verdeBase);
    }//GEN-LAST:event_verMasCMouseExited

    private void verMasPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasPMouseClicked
        jlProductosMouseClicked(evt);
    }//GEN-LAST:event_verMasPMouseClicked

    private void verMasVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasVMouseClicked
        jlVentasMouseClicked(evt);
    }//GEN-LAST:event_verMasVMouseClicked

    private void verMasCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasCMouseClicked
        jlClientesMouseClicked(evt);
    }//GEN-LAST:event_verMasCMouseClicked

    private void jlAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarMouseEntered
        jlAgregar.setBackground(verdeClaro);
    }//GEN-LAST:event_jlAgregarMouseEntered

    private void jlAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarMouseExited
        jlAgregar.setBackground(verdeBase);
    }//GEN-LAST:event_jlAgregarMouseExited

    private void jlModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlModificarMouseEntered
        jlModificar.setBackground(verdeClaro);
    }//GEN-LAST:event_jlModificarMouseEntered

    private void jlModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlModificarMouseExited
        jlModificar.setBackground(verdeBase);
    }//GEN-LAST:event_jlModificarMouseExited

    private void jlEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEliminarMouseEntered
        jlEliminar.setBackground(verdeClaro);
    }//GEN-LAST:event_jlEliminarMouseEntered

    private void jlEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEliminarMouseExited
        jlEliminar.setBackground(verdeBase);
    }//GEN-LAST:event_jlEliminarMouseExited

    private void jlListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarMouseEntered
        jlListar.setBackground(verdeClaro);
    }//GEN-LAST:event_jlListarMouseEntered

    private void jlListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarMouseExited
        jlListar.setBackground(verdeBase);
    }//GEN-LAST:event_jlListarMouseExited

    private void jlCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarSesionMouseClicked
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlCerrarSesionMouseClicked

    private void jlListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarMouseClicked
        jtpEscritorio.setSelectedIndex(4);
        llenarTabla();
    }//GEN-LAST:event_jlListarMouseClicked

    private void jlListarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlListarClienteMouseClicked

    private void jlListarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarClienteMouseEntered
        jlListarCliente.setBackground(verdeClaro);
    }//GEN-LAST:event_jlListarClienteMouseEntered

    private void jlListarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarClienteMouseExited
        jlListarCliente.setBackground(verdeBase);
    }//GEN-LAST:event_jlListarClienteMouseExited

    private void jlAgregarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarClienteMouseEntered
        jlAgregarCliente.setBackground(verdeClaro);
    }//GEN-LAST:event_jlAgregarClienteMouseEntered

    private void jlAgregarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarClienteMouseExited
        jlAgregarCliente.setBackground(verdeBase);
    }//GEN-LAST:event_jlAgregarClienteMouseExited

    private void jlModificarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlModificarClienteMouseEntered
        jlModificarCliente.setBackground(verdeClaro);
    }//GEN-LAST:event_jlModificarClienteMouseEntered

    private void jlModificarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlModificarClienteMouseExited
        jlModificarCliente.setBackground(verdeBase);
    }//GEN-LAST:event_jlModificarClienteMouseExited

    private void jlEliminarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEliminarClienteMouseEntered
        jlEliminarCliente.setBackground(verdeClaro);
    }//GEN-LAST:event_jlEliminarClienteMouseEntered

    private void jlEliminarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEliminarClienteMouseExited
        jlEliminarCliente.setBackground(verdeBase);
    }//GEN-LAST:event_jlEliminarClienteMouseExited

    private void RegistrarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarVentaMouseClicked
        //
    }//GEN-LAST:event_RegistrarVentaMouseClicked

    private void RegistrarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarVentaMouseEntered
        RegistrarVenta.setBackground(verdeClaro);
    }//GEN-LAST:event_RegistrarVentaMouseEntered

    private void RegistrarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarVentaMouseExited
        RegistrarVenta.setBackground(verdeBase);
    }//GEN-LAST:event_RegistrarVentaMouseExited

    private void DetVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DetVentaMouseClicked

    private void DetVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetVentaMouseEntered
        DetVenta.setBackground(verdeClaro);
    }//GEN-LAST:event_DetVentaMouseEntered

    private void DetVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetVentaMouseExited
        DetVenta.setBackground(verdeBase);
    }//GEN-LAST:event_DetVentaMouseExited

    private void EliminarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarVentaMouseClicked

    private void EliminarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarVentaMouseEntered
        EliminarVenta.setBackground(verdeClaro);
    }//GEN-LAST:event_EliminarVentaMouseEntered

    private void EliminarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarVentaMouseExited
        EliminarVenta.setBackground(verdeBase);
    }//GEN-LAST:event_EliminarVentaMouseExited

    private void jlProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProductosMouseExited
        jlProductos.setBackground(grisBase);
    }//GEN-LAST:event_jlProductosMouseExited

    private void jlProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProductosMouseEntered
        jlProductos.setBackground(grisClaro);
    }//GEN-LAST:event_jlProductosMouseEntered

    private void jlProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProductosMouseClicked
        jtpEscritorio.setSelectedIndex(3);
    }//GEN-LAST:event_jlProductosMouseClicked

    private void jlListarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlListarVentaMouseClicked

    private void jlListarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarVentaMouseEntered
        jlListarVenta.setBackground(verdeClaro);
    }//GEN-LAST:event_jlListarVentaMouseEntered

    private void jlListarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarVentaMouseExited
        jlListarVenta.setBackground(verdeBase);
    }//GEN-LAST:event_jlListarVentaMouseExited

    private void jlBusquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBusquedaMouseEntered
        jlBusqueda.setBackground(verdeClaro);
        jlBusqueda.setIcon(new ImageIcon(getClass().getResource("/Image/busqueda - blanco.png")));
    }//GEN-LAST:event_jlBusquedaMouseEntered

    private void jlBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBusquedaMouseExited
        jlBusqueda.setBackground(Color.white);
        jlBusqueda.setIcon(new ImageIcon(getClass().getResource("/Image/busqueda - gris.png")));
    }//GEN-LAST:event_jlBusquedaMouseExited

    private void jlBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBusquedaMouseClicked
        borrarFila();
        for (Producto pro : pd.listarProducto()) {
            if (pro.getNombreProducto().toLowerCase().contains(jtfBuscador.getText()) || pro.getNombreProducto().toUpperCase().contains(jtfBuscador.getText()) ) {
                Modelo.addRow(new Object[]{
                    pro.getIdProducto(),
                    pro.getNombreProducto(),
                    pro.getDescripcion(),
                    pro.getPrecioActual(),
                    pro.getStock()
                });
            }
        }
    }//GEN-LAST:event_jlBusquedaMouseClicked

    private void jlAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarMouseClicked
        jtpEscritorio.setSelectedIndex(5);
    }//GEN-LAST:event_jlAgregarMouseClicked

    private void jLBtnAgregarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBtnAgregarProdMouseEntered
       jLBtnAgregarProd.setBackground(verdeClaro);
    }//GEN-LAST:event_jLBtnAgregarProdMouseEntered

    private void jLBtnAgregarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBtnAgregarProdMouseExited
        jLBtnAgregarProd.setBackground(verdeBase);
    }//GEN-LAST:event_jLBtnAgregarProdMouseExited

    private void jlModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlModificarMouseClicked
        jtpEscritorio.setSelectedIndex(7);
    }//GEN-LAST:event_jlModificarMouseClicked

    private void jLBtnModificarModProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBtnModificarModProdMouseEntered
        jLBtnModificarModProd.setBackground(verdeClaro);
    }//GEN-LAST:event_jLBtnModificarModProdMouseEntered

    private void jLBtnModificarModProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBtnModificarModProdMouseExited
        jLBtnModificarModProd.setBackground(verdeBase);
    }//GEN-LAST:event_jLBtnModificarModProdMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.put("nimbusBlueGrey", new Color(51, 51, 76));
                    UIManager.put("control", new Color(0, 150, 136));
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel DetVenta;
    private javax.swing.JLabel EliminarVenta;
    private javax.swing.JLabel RegistrarVenta;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JLabel fravemaxLogo;
    private javax.swing.JLabel jLAgregarProducto;
    private javax.swing.JLabel jLBtnAgregarProd;
    private javax.swing.JLabel jLBtnModificarModProd;
    private javax.swing.JLabel jLBuscarProdModProd;
    private javax.swing.JLabel jLDescripcionAP;
    private javax.swing.JLabel jLDescripcionModProd;
    private javax.swing.JLabel jLModificarProd;
    private javax.swing.JLabel jLNombreProdModProd;
    private javax.swing.JLabel jLNombreProductoAP;
    private javax.swing.JLabel jLPrecioActualAP;
    private javax.swing.JLabel jLPrecioActualModProd;
    private javax.swing.JLabel jLStockAP;
    private javax.swing.JLabel jLStockModProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFravemax;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFDescripcionAgrProd;
    private javax.swing.JTextField jTFDescripcionModProd;
    private javax.swing.JTextField jTFNombreProdModProd;
    private javax.swing.JTextField jTFNombreProductoAgrProd;
    private javax.swing.JTextField jTFPrecioActualAgrProd;
    private javax.swing.JTextField jTFPrecioActualModProd;
    private javax.swing.JTextField jTFStockAgrProd;
    private javax.swing.JTextField jTFStockModProd;
    private javax.swing.JComboBox<Producto> jcbProductos;
    private javax.swing.JLabel jlAgregar;
    private javax.swing.JLabel jlAgregarCliente;
    private javax.swing.JLabel jlBusqueda;
    private javax.swing.JLabel jlCerrarSesion;
    private javax.swing.JLabel jlClientes;
    private javax.swing.JLabel jlDetalles;
    private javax.swing.JLabel jlEliminar;
    private javax.swing.JLabel jlEliminarCliente;
    private javax.swing.JLabel jlEliminarVenta;
    private javax.swing.JLabel jlGestionV;
    private javax.swing.JLabel jlInicio;
    private javax.swing.JLabel jlListar;
    private javax.swing.JLabel jlListarCliente;
    private javax.swing.JLabel jlListarVenta;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JLabel jlModificar;
    private javax.swing.JLabel jlModificarCliente;
    private javax.swing.JLabel jlProductos;
    private javax.swing.JLabel jlRegistrar;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JLabel jlVentaIcon1;
    private javax.swing.JLabel jlVentaIcon2;
    private javax.swing.JLabel jlVentaIcon3;
    private javax.swing.JLabel jlVentas;
    private javax.swing.JTable jtListaPro;
    private javax.swing.JTextField jtfBuscador;
    private javax.swing.JPanel jtpAgregarPro;
    private javax.swing.JPanel jtpClientes;
    private javax.swing.JTabbedPane jtpEscritorio;
    private javax.swing.JPanel jtpInicio;
    private javax.swing.JPanel jtpListaP;
    private javax.swing.JPanel jtpModPro;
    private javax.swing.JPanel jtpProductos;
    private javax.swing.JPanel jtpVentas;
    private javax.swing.JLabel rectanguloV1;
    private javax.swing.JLabel rectanguloV2;
    private javax.swing.JLabel rectanguloV3;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel textA;
    private javax.swing.JLabel textClienteA;
    private javax.swing.JLabel textClienteE;
    private javax.swing.JLabel textClienteM;
    private javax.swing.JLabel textE;
    private javax.swing.JLabel textM;
    private javax.swing.JLabel textVentaA;
    private javax.swing.JLabel textVentaD;
    private javax.swing.JLabel textVentaE;
    private javax.swing.JLabel verMasC;
    private javax.swing.JLabel verMasP;
    private javax.swing.JLabel verMasV;
    // End of variables declaration//GEN-END:variables

    private void borrarFila() {
            for (int f = jtListaPro.getRowCount() - 1; f >= 0; f--) {
                Modelo.removeRow(f);
            }
    }

    private void llenarText() {
        text1.setText("<html>Registrar productos: Los usuarios podrán agregar nuevos productos al inventario proporcionando información como nombre, descripción, precio y cantidad disponible</html>");
        text2.setText("<html>Realizar ventas: Los usuarios podrán registrar las ventas de productos a los clientes. el cliente que realiza la compra y la fecha de venta</html>");
        text3.setText("<html>Administrar Clientes: Los usuarios podrán agregar, modificar y eliminar información de los clientes, como nombre, apellido, dirección y número de teléfono</html>");
        textA.setText("<html>Ingresar nuevos productos a la base de datos</html>");
        textM.setText("<html>Actualizar los datos de los productos en la base de datos</html>");
        textE.setText("<html>Borrado logico de los productos en la base de datos</html>");
        textClienteA.setText("<html>Registrar Clientes: Permite agregar Clientes nuevos, ingresando nombre, apellido....</html>");
        textClienteM.setText("<html>Modificar datos: Permite modificar la informacion almacenda de los Clientes</html>");
        textClienteE.setText("<html>Eliminar Clientes: Permite eliminar a los Clientes de manera Lógica</html>");
        textVentaA.setText("<html>Registrar Venta: Permite ingresar los datos de una venta como producto, precio y cantidad</html>");
        textVentaD.setText("<html>Detallar Venta: Lista completa de los datos de una venta registrada</html>");
        textVentaE.setText("<html>Eliminar Venta: Permite dar de baja el registro de una venta para su posterior eliminación");
    }
    
    private void llenarCombo(){
        for (Producto pro : pd.listarProducto()){
            jcbProductos.addItem(pro);
        }
    }
}
