/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author ROMI
 */
public class Menu extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        text1.setText("<html>Agregar, actualizar y eliminar productos.</html>");
        text2.setText("<html>Registrar ventas, historial de ventas y actualizar detalles.</html>");
        text3.setText("<html>Administrar datos de los clientes y lista de clientes</html>");
        textAgregaCli.setText("<html> Agregar, actualizar y eliminar Clientes.</html>");
        textModificaC.setText("<html> Modificar datos de los Clientes.</html>");
        textEliminaC.setText("<html> Eliminar Clientes.</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jPanelFravemax = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlNombreUsuario = new javax.swing.JLabel();
        jlFravemax = new javax.swing.JLabel();
        jlSalir = new javax.swing.JLabel();
        jlMinimizar = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jPanelProductos = new javax.swing.JPanel();
        jlProductos = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jlClientes = new javax.swing.JLabel();
        jPanelVentas = new javax.swing.JPanel();
        jlVentas = new javax.swing.JLabel();
        jPanelCerraSesion = new javax.swing.JPanel();
        jlCerrarSesion = new javax.swing.JLabel();
        jPanelInicio = new javax.swing.JPanel();
        jlInicio = new javax.swing.JLabel();
        jtpEscritorio = new javax.swing.JTabbedPane();
        jtpInicio = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verMasC = new javax.swing.JLabel();
        verMasV = new javax.swing.JLabel();
        verMasP = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtpVentas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtpClientes = new javax.swing.JPanel();
        jtpInicio1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        Modificar = new javax.swing.JLabel();
        AgregarC = new javax.swing.JLabel();
        textEliminaC = new javax.swing.JLabel();
        textModificaC = new javax.swing.JLabel();
        textAgregaCli = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLRectAgregaC = new javax.swing.JLabel();
        jLRModificaC = new javax.swing.JLabel();
        jLEliminaC = new javax.swing.JLabel();
        ListarClientes = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtpProductos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFravemax.setBackground(new java.awt.Color(0, 150, 136));
        jPanelFravemax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFravemax.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelFravemaxMouseDragged(evt);
            }
        });
        jPanelFravemax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFravemaxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelFravemaxMouseReleased(evt);
            }
        });
        jPanelFravemax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanelFravemax.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanelFravemax.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 100));

        jPanelUsuario.setBackground(new java.awt.Color(0, 150, 136));
        jPanelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/circulo-de-usuario.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanelUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        jlNombreUsuario.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNombreUsuario.setText("nombre de usuario");
        jlNombreUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlNombreUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelUsuario.add(jlNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 200, 100));

        jPanelFravemax.add(jPanelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jlFravemax.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlFravemax.setForeground(new java.awt.Color(255, 255, 255));
        jlFravemax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFravemax.setText("BIENVENIDO A FRAVEMAX");
        jlFravemax.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanelFravemax.add(jlFravemax, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 20));

        jlSalir.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("X");
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
        });
        jPanelFravemax.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 30));

        jlMinimizar.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jlMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setText("_");
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseExited(evt);
            }
        });
        jPanelFravemax.add(jlMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 30));

        BackGround.add(jPanelFravemax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jPanelOpciones.setBackground(new java.awt.Color(51, 51, 76));
        jPanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProductos.setBackground(new java.awt.Color(51, 51, 76));
        jPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlProductos.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlProductos.setForeground(new java.awt.Color(255, 255, 255));
        jlProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Productos.png"))); // NOI18N
        jlProductos.setText("Productos");
        jlProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlProductos.setIconTextGap(15);
        jlProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlProductosMouseExited(evt);
            }
        });
        jPanelProductos.add(jlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanelOpciones.add(jPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 40));

        jPanelClientes.setBackground(new java.awt.Color(51, 51, 76));
        jPanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlClientes.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlClientes.setForeground(new java.awt.Color(255, 255, 255));
        jlClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarios.png"))); // NOI18N
        jlClientes.setText("Clientes");
        jlClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlClientes.setIconTextGap(15);
        jlClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlClientesMouseExited(evt);
            }
        });
        jPanelClientes.add(jlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanelOpciones.add(jPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 40));

        jPanelVentas.setBackground(new java.awt.Color(51, 51, 76));
        jPanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlVentas.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlVentas.setForeground(new java.awt.Color(255, 255, 255));
        jlVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/carrito-de-compras.png"))); // NOI18N
        jlVentas.setText("Ventas");
        jlVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlVentas.setIconTextGap(15);
        jlVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasMouseExited(evt);
            }
        });
        jPanelVentas.add(jlVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanelOpciones.add(jPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 40));

        jPanelCerraSesion.setBackground(new java.awt.Color(51, 51, 76));
        jPanelCerraSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCerrarSesion.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jlCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/salir-alt.png"))); // NOI18N
        jlCerrarSesion.setText("Cerrar Sesion");
        jlCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlCerrarSesion.setIconTextGap(15);
        jlCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCerrarSesionMouseExited(evt);
            }
        });
        jPanelCerraSesion.add(jlCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanelOpciones.add(jPanelCerraSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 40));

        jPanelInicio.setBackground(new java.awt.Color(51, 51, 76));
        jPanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlInicio.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jlInicio.setForeground(new java.awt.Color(255, 255, 255));
        jlInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Inicio.png"))); // NOI18N
        jlInicio.setText("Inicio");
        jlInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        jlInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlInicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jlInicio.setIconTextGap(15);
        jlInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlInicioMouseExited(evt);
            }
        });
        jPanelInicio.add(jlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jPanelOpciones.add(jPanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 40));

        BackGround.add(jPanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 200, 420));

        jtpInicio.setBackground(new java.awt.Color(255, 255, 255));
        jtpInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Clientes");
        jtpInicio.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Ventas");
        jtpInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Productos");
        jtpInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        verMasC.setBackground(new java.awt.Color(0, 150, 136));
        verMasC.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        verMasC.setForeground(new java.awt.Color(255, 255, 255));
        verMasC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verMasC.setText("Ver mas");
        verMasC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        verMasC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        verMasC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verMasC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verMasC.setOpaque(true);
        verMasC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verMasC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMasCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMasCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verMasCMouseExited(evt);
            }
        });
        jtpInicio.add(verMasC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 80, 30));

        verMasV.setBackground(new java.awt.Color(0, 150, 136));
        verMasV.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        verMasV.setForeground(new java.awt.Color(255, 255, 255));
        verMasV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verMasV.setText("Ver mas");
        verMasV.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        verMasV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        verMasV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verMasV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verMasV.setOpaque(true);
        verMasV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verMasV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMasVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMasVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verMasVMouseExited(evt);
            }
        });
        jtpInicio.add(verMasV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, 30));

        verMasP.setBackground(new java.awt.Color(0, 150, 136));
        verMasP.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        verMasP.setForeground(new java.awt.Color(255, 255, 255));
        verMasP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verMasP.setText("Ver mas");
        verMasP.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        verMasP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        verMasP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verMasP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verMasP.setOpaque(true);
        verMasP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verMasP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMasPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMasPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verMasPMouseExited(evt);
            }
        });
        jtpInicio.add(verMasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 30));

        text3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(153, 153, 153));
        text3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpInicio.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 140, 60));

        text2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(153, 153, 153));
        text2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpInicio.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 60));

        text1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(153, 153, 153));
        text1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtpInicio.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 60));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Gestion de ...");
        jtpInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jtpEscritorio.addTab("tab1", jtpInicio);

        jtpVentas.setBackground(new java.awt.Color(255, 255, 255));
        jtpVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ventas");
        jtpVentas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 125, -1, -1));

        jtpEscritorio.addTab("tab2", jtpVentas);

        jtpClientes.setBackground(new java.awt.Color(255, 255, 255));
        jtpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtpInicio1.setBackground(new java.awt.Color(255, 255, 255));
        jtpInicio1.setPreferredSize(new java.awt.Dimension(600, 400));
        jtpInicio1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Eliminar Clientes");
        jtpInicio1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Modificar Clientes");
        jtpInicio1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Agregar Clientes");
        jtpInicio1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Eliminar.setBackground(new java.awt.Color(0, 150, 136));
        Eliminar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eliminar.setText("Eliminar");
        Eliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setOpaque(true);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarMouseExited(evt);
            }
        });
        jtpInicio1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 80, 30));

        Modificar.setBackground(new java.awt.Color(0, 150, 136));
        Modificar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modificar.setText("Modificar");
        Modificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modificar.setOpaque(true);
        Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarMouseExited(evt);
            }
        });
        jtpInicio1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, 30));

        AgregarC.setBackground(new java.awt.Color(0, 150, 136));
        AgregarC.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        AgregarC.setForeground(new java.awt.Color(255, 255, 255));
        AgregarC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarC.setText("Agregar");
        AgregarC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AgregarC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        AgregarC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AgregarC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarC.setOpaque(true);
        AgregarC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarCMouseExited(evt);
            }
        });
        jtpInicio1.add(AgregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 30));

        textEliminaC.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        textEliminaC.setForeground(new java.awt.Color(153, 153, 153));
        textEliminaC.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpInicio1.add(textEliminaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 140, 60));

        textModificaC.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        textModificaC.setForeground(new java.awt.Color(153, 153, 153));
        textModificaC.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jtpInicio1.add(textModificaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 60));

        textAgregaCli.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        textAgregaCli.setForeground(new java.awt.Color(153, 153, 153));
        textAgregaCli.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textAgregaCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtpInicio1.add(textAgregaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 60));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Gestion de Clientes");
        jtpInicio1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 30));

        jLRectAgregaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio1.add(jLRectAgregaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLRModificaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio1.add(jLRModificaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLEliminaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpInicio1.add(jLEliminaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        ListarClientes.setBackground(new java.awt.Color(0, 150, 136));
        ListarClientes.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        ListarClientes.setForeground(new java.awt.Color(255, 255, 255));
        ListarClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListarClientes.setText("Listar Clientes");
        ListarClientes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ListarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 150, 136), null, null));
        ListarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListarClientes.setOpaque(true);
        ListarClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ListarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListarClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListarClientesMouseExited(evt);
            }
        });
        jtpInicio1.add(ListarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 130, 30));

        jtpClientes.add(jtpInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rectangulo.jpg"))); // NOI18N
        jtpClientes.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jtpEscritorio.addTab("tab3", jtpClientes);

        jtpProductos.setBackground(new java.awt.Color(255, 255, 255));
        jtpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Productos");
        jtpProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 137, -1, -1));

        jtpEscritorio.addTab("tab4", jtpProductos);

        BackGround.add(jtpEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 53, 600, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProductosMouseEntered
        jPanelProductos.setBackground(new Color(66, 66, 76));
    }//GEN-LAST:event_jlProductosMouseEntered

    private void jlProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProductosMouseExited
        jPanelProductos.setBackground(new Color(51, 51, 76));
    }//GEN-LAST:event_jlProductosMouseExited

    private void jlVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMouseEntered
        jPanelVentas.setBackground(new Color(66, 66, 76));
    }//GEN-LAST:event_jlVentasMouseEntered

    private void jlVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMouseExited
        jPanelVentas.setBackground(new Color(51, 51, 76));
    }//GEN-LAST:event_jlVentasMouseExited

    private void jlClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseEntered
        jPanelClientes.setBackground(new Color(66, 66, 76));
    }//GEN-LAST:event_jlClientesMouseEntered

    private void jlClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseExited
        jPanelClientes.setBackground(new Color(51, 51, 76));
    }//GEN-LAST:event_jlClientesMouseExited

    private void jlCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarSesionMouseEntered
        jPanelCerraSesion.setBackground(new Color(66, 66, 76));
    }//GEN-LAST:event_jlCerrarSesionMouseEntered

    private void jlCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarSesionMouseExited
        jPanelCerraSesion.setBackground(new Color(51, 51, 76));
    }//GEN-LAST:event_jlCerrarSesionMouseExited

    private void jlProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProductosMouseClicked
        jtpEscritorio.setSelectedIndex(3);
    }//GEN-LAST:event_jlProductosMouseClicked

    private void jlVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMouseClicked
        jtpEscritorio.setSelectedIndex(1);
    }//GEN-LAST:event_jlVentasMouseClicked

    private void jlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseClicked
        jtpEscritorio.setSelectedIndex(2);
    }//GEN-LAST:event_jlClientesMouseClicked

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        jlSalir.setOpaque(true);
        jlSalir.setBackground(Color.red);
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        jlSalir.setOpaque(false);
        jlSalir.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseEntered
        jlMinimizar.setOpaque(true);
        jlMinimizar.setBackground(new Color(10, 160, 140));
    }//GEN-LAST:event_jlMinimizarMouseEntered

    private void jlMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseExited
        jlMinimizar.setOpaque(false);
        jlMinimizar.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_jlMinimizarMouseExited

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseEntered
        jPanelInicio.setBackground(new Color(66, 66, 76));
    }//GEN-LAST:event_jlInicioMouseEntered

    private void jlInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseExited
        jPanelInicio.setBackground(new Color(51, 51, 76));
    }//GEN-LAST:event_jlInicioMouseExited

    private void jlInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseClicked
        jtpEscritorio.setSelectedIndex(0);
    }//GEN-LAST:event_jlInicioMouseClicked

    private void jPanelFravemaxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFravemaxMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        jPanelFravemax.setCursor(new Cursor(MOVE_CURSOR));
    }//GEN-LAST:event_jPanelFravemaxMousePressed

    private void jPanelFravemaxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFravemaxMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelFravemaxMouseDragged

    private void jPanelFravemaxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFravemaxMouseReleased
        jPanelFravemax.setCursor(new Cursor(DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelFravemaxMouseReleased

    private void verMasPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasPMouseEntered
        verMasP.setBackground(new Color(10,170,140));
    }//GEN-LAST:event_verMasPMouseEntered

    private void verMasPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasPMouseExited
        verMasP.setBackground(new Color(0,150,136));
    }//GEN-LAST:event_verMasPMouseExited

    private void verMasVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasVMouseEntered
        verMasV.setBackground(new Color(10,170,140));
    }//GEN-LAST:event_verMasVMouseEntered

    private void verMasVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasVMouseExited
        verMasV.setBackground(new Color(0,150,136));
    }//GEN-LAST:event_verMasVMouseExited

    private void verMasCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasCMouseEntered
        verMasC.setBackground(new Color(10,170,140));
    }//GEN-LAST:event_verMasCMouseEntered

    private void verMasCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasCMouseExited
        verMasC.setBackground(new Color(0,150,136));
    }//GEN-LAST:event_verMasCMouseExited

    private void verMasPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasPMouseClicked
        jlProductosMouseClicked(evt);
    }//GEN-LAST:event_verMasPMouseClicked

    private void verMasVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasVMouseClicked
        jlVentasMouseClicked(evt);
    }//GEN-LAST:event_verMasVMouseClicked

    private void verMasCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMasCMouseClicked
        jlClientesMouseClicked(evt);
    }//GEN-LAST:event_verMasCMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMouseClicked

    private void EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMouseEntered

    private void EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMouseExited

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseClicked

    private void ModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseEntered

    private void ModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseExited

    private void AgregarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCMouseClicked

    private void AgregarCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCMouseEntered

    private void AgregarCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCMouseExited

    private void ListarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarClientesMouseClicked

    private void ListarClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarClientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarClientesMouseEntered

    private void ListarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarClientesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarClientesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarC;
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel ListarClientes;
    private javax.swing.JLabel Modificar;
    private javax.swing.JLabel jLEliminaC;
    private javax.swing.JLabel jLRModificaC;
    private javax.swing.JLabel jLRectAgregaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCerraSesion;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelFravemax;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlCerrarSesion;
    private javax.swing.JLabel jlClientes;
    private javax.swing.JLabel jlFravemax;
    private javax.swing.JLabel jlInicio;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JLabel jlProductos;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JLabel jlVentas;
    private javax.swing.JPanel jtpClientes;
    private javax.swing.JTabbedPane jtpEscritorio;
    private javax.swing.JPanel jtpInicio;
    private javax.swing.JPanel jtpInicio1;
    private javax.swing.JPanel jtpProductos;
    private javax.swing.JPanel jtpVentas;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel textAgregaCli;
    private javax.swing.JLabel textEliminaC;
    private javax.swing.JLabel textModificaC;
    private javax.swing.JLabel verMasC;
    private javax.swing.JLabel verMasP;
    private javax.swing.JLabel verMasV;
    // End of variables declaration//GEN-END:variables
}
